version: "3"

services:
  redis:
    image: redis:alpine
    container_name: node_limit_redis
    ports:
      - 6379:6379
    command: redis-server --requirepass @@123456
    volumes:
      - /var/www/volumes/redis:/data
